#
# _config.yml for Lucky Logo
#

exclude: [ "CNAME" ]
production_url: https://lucky.logosear.ch
sharing_targets: [ "reddit", "pinboard" ]
title: Lucky Logo
markdown: kramdown
plugins:
  - jekyll-redirect-from
redirect_from:
  json: false
theme: null
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "simple"

