export enum ErrorCode {
    NO_LOGO_FOUND = 'NO_LOGO_FOUND',
    HOST_NOT_FOUND = 'HOST_NOT_FOUND',
    INVALID_URL = 'INVALID_URL',
    MISSING_URL_PARAM = 'MISSING_URL_PARAM',
    UNKNOWN = 'UNKNOWN',
};
